#include"TIVAC.h"

typedef unsigned int uint32_t;
#define SET_BIT(var,BIT)     var|=(1<<BIT)
#define CLR_BIT(var,BIT)     var&=~(1<<BIT)
#define Toggle_BIT(var,BIT)  var^=(1<<BIT)
#define Get_BIT(var,BIT)    (var>>BIT)&1

void initPortA(){
	SYSCTL_RCGCGPIO_R= SYSCTL_RCGCGPIO_R|0x01;
	while((SYSCTL_PRGPIO_R & 0X01)==0){};
		GPIO_PORTA_CR_R=0xFF;
		GPIO_PORTA_DEN_R=0xFF;
		GPIO_PORTA_AFSEL_R=0x00;
		GPIO_PORTA_PCTL_R=0x00;
		GPIO_PORTA_AMSEL_R=0x00;
}

void initPortB(){
	SYSCTL_RCGCGPIO_R=SYSCTL_RCGCGPIO_R|0x02;
	while((SYSCTL_PRGPIO_R & 0X02)==0){};
		GPIO_PORTB_CR_R=0xFF;
		GPIO_PORTB_DEN_R=0xFF;
		GPIO_PORTB_AFSEL_R=0x00;
		GPIO_PORTB_PCTL_R=0x00;
		GPIO_PORTB_AMSEL_R=0x00;
}

void initPortC(){
	SYSCTL_RCGCGPIO_R=SYSCTL_RCGCGPIO_R|0x04;
	while((SYSCTL_PRGPIO_R & 0X04)==0){};
		GPIO_PORTC_CR_R=0xFF;
		GPIO_PORTC_DEN_R=0xFF;
		GPIO_PORTC_AFSEL_R=0x00;
		GPIO_PORTC_PCTL_R=0x00;
		GPIO_PORTC_AMSEL_R=0x00;
}

void initPortD(){
	SYSCTL_RCGCGPIO_R=SYSCTL_RCGCGPIO_R|0x08;
	while((SYSCTL_PRGPIO_R & 0X08)==0){};
		GPIO_PORTD_CR_R=0xFF;
		GPIO_PORTD_DEN_R=0xFF;
		GPIO_PORTD_AFSEL_R=0x00;
		GPIO_PORTD_PCTL_R=0x00;
		GPIO_PORTD_AMSEL_R=0x00;
}

void initPortE(){
	SYSCTL_RCGCGPIO_R=SYSCTL_RCGCGPIO_R|0x10;
	while((SYSCTL_PRGPIO_R & 0X10)==0){};
		GPIO_PORTE_CR_R=0x3F;
		GPIO_PORTE_DEN_R=0x3F;
		GPIO_PORTE_AFSEL_R=0x00;
		GPIO_PORTE_PCTL_R=0x00;
		GPIO_PORTE_AMSEL_R=0x00;
}

void initPortF(){
	SYSCTL_RCGCGPIO_R=SYSCTL_RCGCGPIO_R|0x20;
	while((SYSCTL_PRGPIO_R & 0X20)==0){};
		GPIO_PORTF_CR_R=0x1F;
		GPIO_PORTF_DEN_R=0x1F;
		GPIO_PORTF_AFSEL_R=0x00;
		GPIO_PORTF_PCTL_R=0x00;
		GPIO_PORTF_AMSEL_R=0x00;	
}
